spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=the_gamer_dev_default
    username: postgres
    password: postgres

    hikari:
      maximum-pool-size: 10
      connectionTimeout: 30000
      minimumIdle: 1
      idleTimeout: 30000
      maxLifetime: 1800000

  jpa:
    properties:
      hibernate.jdbc.batch_size: 50
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.use_sql_comments: true

  liquibase:
    contexts: dev
    drop-first: true
    enabled: true